name: BuildTest
on:
  pull_request: null
env:
  cache-version: v1
jobs:
  build-android:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:2018.4.13f1-android
    steps:
    - uses: actions/checkout@v1
    - run: echo "${{ secrets.UNITY_2018_X_ULF_BASE64 }}" | base64 -d > /Unity_v2018.x.ulf
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile /Unity_v2018.x.ulf || exit 0
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/unity-build/Library
        key: ${{ runner.os }}-android-${{ env.cache-version }}
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath $(pwd)/unity-build -buildTarget android -executeMethod BuildPlayer.Build
  build-ios:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:2018.4.13f1-ios
    steps:
    - uses: actions/checkout@v1
    - run: echo "${{ secrets.UNITY_2018_X_ULF_BASE64 }}" | base64 -d > /Unity_v2018.x.ulf
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile /Unity_v2018.x.ulf || exit 0
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/unity-build/Library
        key: ${{ runner.os }}-ios-${{ env.cache-version }}
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath $(pwd)/unity-build -buildTarget ios -executeMethod BuildPlayer.Build
